# Generated by Django 4.0.5 on 2022-06-22 23:57

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postSlug', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('overview', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(default=True, upload_to='static/imgs/posts')),
                ('smalltitle', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='videosYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
