# Generated by Django 4.0.3 on 2022-05-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='static/imgs/pc'),
        ),
    ]
