# Generated by Django 4.0.3 on 2022-05-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='static/imgs/posts'),
        ),
    ]
