# Generated by Django 4.0.5 on 2022-06-28 15:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('book', 'book'), ('laptop', 'laptop'), ('pc', 'pc'), ('shirt', 'shirt'), ('mug', 'mug'), ('laptop', 'laptop'), ('accessories', 'accessories'), ('offers', 'offers')], default='', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=300)),
                ('phone', models.CharField(max_length=11)),
                ('whatsapp', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True, max_length=300, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shraby Company', 'Shraby Company '), ('New Vision', 'New Vision'), ('BookStore', 'BookStore')], default='', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oldPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('product_information', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('productCondition', models.CharField(blank=True, choices=[('جديد', 'جديد'), ('مستعمل بحالة الجديد', 'مستعمل بحالة الجديد'), ('مستعمل بحالة الجيد', 'مستعمل بحالة الجيد')], max_length=50, null=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to=store.models.image_Path)),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to=store.models.image_Path)),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to=store.models.image_Path)),
                ('thumbnail3', models.ImageField(blank=True, null=True, upload_to=store.models.image_Path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('company', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.company')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.checkout')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
