# Generated by Django 4.0.3 on 2022-05-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='static/imgs/laptop'),
        ),
        migrations.AddField(
            model_name='mug',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='static/imgs/mug'),
        ),
        migrations.AddField(
            model_name='pc',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='static/imgs/pc'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to='static/imgs/shirt'),
        ),
    ]
