# Generated by Django 4.0.3 on 2022-06-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('book', 'book'), ('laptop', 'laptop'), ('pc', 'pc'), ('shirt', 'shirt'), ('mug', 'mug'), ('laptop', 'laptop')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='products_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
