# Generated by Django 4.0.5 on 2022-06-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCondition',
            field=models.CharField(blank=True, choices=[('new', 'جديد'), ('used like new', 'جديد فى حالة المستعمل'), ('used', 'مستعمل')], max_length=50, null=True),
        ),
    ]
