# Generated by Django 4.0.5 on 2022-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='static/imgs/product/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
