# Generated by Django 4.0.5 on 2022-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_alter_product_options_orderitem_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
