# Generated by Django 4.0.5 on 2022-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(blank=True, default=1, upload_to='static/imgs/product/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, default=1, upload_to='static/imgs/product/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(blank=True, default=1, upload_to='static/imgs/product/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
