# Generated by Django 4.0.5 on 2022-06-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_productcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCondition',
            field=models.CharField(blank=True, choices=[('جديد', 'جديد'), ('مستعمل بحالة الجديد', 'مستعمل بحالة الجديد'), ('مستعمل', 'مستعمل')], max_length=50, null=True),
        ),
    ]
