# Generated by Django 4.0.5 on 2022-06-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_name_alter_checkout_products_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('book', 'book'), ('laptop', 'laptop'), ('pc', 'pc'), ('shirt', 'shirt'), ('mug', 'mug'), ('laptop', 'laptop'), ('accessories', 'accessories'), ('offers', 'offers')], default='', max_length=50),
        ),
    ]
