# Generated by Django 4.0.5 on 2022-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('Shraby Company', 'Shraby Company '), ('New Vision', 'New Vision'), ('BookStore', 'BookStore')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCondition',
            field=models.CharField(blank=True, choices=[('جديد', 'جديد'), ('مستعمل بحالة الجديد', 'مستعمل بحالة الجديد'), ('مستعمل بحالة الجيد', 'مستعمل بحالة الجيد')], max_length=50, null=True),
        ),
    ]
