# Generated by Django 4.0.5 on 2022-06-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='static/imgs/product/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='static/imgs/product/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='static/imgs/product/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='ProductImg',
        ),
    ]
