# Generated by Django 4.0.5 on 2022-06-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_thumbnail1_alter_product_thumbnail2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/product/%Y/%m/%d'),
        ),
    ]
