# Generated by Django 4.0.5 on 2022-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_thumbnail_alter_product_thumbnail1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default=1, upload_to='static/imgs/product/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
