# Generated by Django 4.0.5 on 2022-06-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_thumbnail_alter_product_thumbnail1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
