# Generated by Django 4.0.5 on 2022-06-19 14:27

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.image_Path),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.image_Path),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.image_Path),
        ),
    ]
